add option to choose program to run the container (--runcmd)
if parameter is not set, it looks for podman,orbstack and docker

diff --git a/evb b/evb
--- a/evb
+++ b/evb
@@ -33,6 +33,8 @@ available options:
                            run VoxBox with -e SPEC=spec/classes/supermodule_spec.rb
   --volume vol  : specify an additional volume to put into the container
                   see podman man page how to specify 'vol'. (no path magic is done ;)) 
+  --runcmd      : this lets you change the program used to start the container
+                  if not set explicit it looks for podman, orbstack and finally docker.
 
 available command:
    help  : print this help message and exit
@@ -45,7 +47,7 @@ EOF
 
 run_container () {
   P=$(get_path $PWD)
-  command="podman run -it --rm $(sed "s|=${P}/|=|g" <<< "${PODENV}") -v ${P}:/repo:Z ${PODOPTIONS} ${PODIMAGE} ${VOXBOXCOMMAND}"
+  command="${RUNCMD} run -it --rm $(sed "s|=${P}/|=|g" <<< "${PODENV}") -v ${P}:/repo:Z ${PODOPTIONS} ${PODIMAGE} ${VOXBOXCOMMAND}"
   if [ ${NOOP} -eq 0 ] ; then
      ${command}
   else
@@ -54,6 +56,7 @@ run_container () {
      echo
   fi
 }
+
 
 # get options
 NOOP=0
@@ -69,6 +72,11 @@ while [[ $# -gt 0 ]]; do
     ;;
     --noop)
        NOOP=1
+       shift
+    ;;
+    --runcmd)
+       shift
+       RUNCMD=${1}
        shift
     ;;
     --entrypoint)
@@ -97,5 +105,19 @@ while [[ $# -gt 0 ]]; do
     ;;
   esac
 done
+
+# lets see what we have as default runcmd:
+if [ -n "${RUNCMD}" ] ; then
+  true
+elif [ -n $(which podman) ] ; then 
+  RUNCMD='podman'
+elif [ -n $(which orbstack) ] ; then
+  RUNCMD='orbstack'
+elif [ -n $(which docker) ] ; then
+  RUNCMD='docker'
+else
+  echo "ERROR: could not find podman/orbstack or docker to start container" >&2
+  exit 200
+fi
 
 run_container
